export const langEn = {
  search: {
    button: "Search",
    input: "Search city",
  },
  shortDay: {
    0: "Sun",
    1: "Mon",
    2: "Tues",
    3: "Wed",
    4: "Thurs",
    5: "Fri",
    6: "Sat",
  },
  month: {
    0: "January",
    1: "February",
    2: "March",
    3: "April",
    4: "May",
    5: "June",
    6: "July",
    7: "August",
    8: "September",
    9: "October",
    10: "November",
    11: "December",
  },
  summary: {
    feels: "Feels like: ",
    wind: "Wind: ",
    speed: "m/s",
    humidity: "Humidity: ",
  },
  fullDay: {
    0: "Sunday",
    1: "Monday",
    2: "Tuesday",
    3: "Wednesday",
    4: "Thursday",
    5: "Friday",
    6: "Saturday",
  },
  coordinates: {
    latit: "Latitude: ",
    longit: "Longitude: ",
  },
};
